### ISSUE TITLE
`npm run buildtest` fails after a fresh `npm i`

### ISSUE THREAD

**Issue by thgreasi** [grantila/u2f-api#10]
Fails with:
```
node_modules/already/dist/index.js:35
    async function _then(t) {
          ^^^^^^^^

SyntaxError: Unexpected token function
```
It also seems that the package-lock.json & package.json are out of sync for the `already` package.
```
node --version
v6.14.1
npm --version
5.8.0
```

**Comment by thgreasi** [comment]
Upgrading to node v8 fixes the issue.
It would be great if this was in package.json or even in README

**Comment by grantila** [comment]
Closing for house-keeping, 8 started LTS over a year ago and 10 has started LTS already.
