### ISSUE TITLE
Any chance you could supply even some basic bundling instructions?

### ISSUE THREAD

**Issue by caballero03** [grantila/u2f-api#12]
I just spent several hours trying to figure out how this library could be used in a browser. 

I've installed nodejs, npm, webpack, yadda, yadda. The tests pass. That is about how far I got.

Tried everything I could find on the topic of transpiling typescript. I am no dummy but new to node and npm and transpiling and bundling. Also, webpack-cli seems to be broken.

What am I missing here?

Any help would be much appreciated.

**Comment by ebeal** [comment]
A compiled version of the library exists in the dist folder, maybe just include and use that. This issue is somewhat dated though, you probably already came to some kind of resolution already.

**Comment by caballero03** [comment]
Thank you @ebeal. I will take a look at it. 

I would really like to find a different library that doesn't use Gulaggle code. I don't trust anything from them anymore.

**Comment by ebeal** [comment]
@caballero03 you may want to start looking into fido 2 (specifically webauthn) if that's the case, u2f is (mostly) a google protocol since firefox dropped their plans for default support.

**Comment by caballero03** [comment]
@ebeal Thank you very much for that. I will look into it when I get some time. Cheers.
