### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by rafaelcmrj** [grantila/u2f-api#13]
Getting the following error when trying to use it with angular2+

`u2f-api.js:532 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').`

**Comment by kgamecarter** [comment]
U2F must run in HTTPS environment.

**Comment by grantila** [comment]
Yeah that's likely the issue, closing for house keeping, please re-open if it's still an issue

**Comment by jakubgs** [comment]
I'm seeing this error as well which prevents U2F from working.

I have an Nginx reverse proxy in front of NextCloud instance, but I also have the [recommended settings](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html):
```php
  'overwrite.cli.url' => 'https://localhost',
  'overwritehost' => 'cloud.example.org',
  'overwriteprotocol' => 'https',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud.example.org',
    2 => 'onlyoffice.example.org',
  ),
  'trusted_proxies' => 
  array (
    0 => '127.0.0.1',
    1 => '10.0.0.0/8',
    2 => '172.17.0.0/16',
  ),
```
How is this supposed to work with a reverse proxy?

**Comment by ffimnsr** [comment]
I also have this issue on wordpress behind reverse proxy, I'm unable to continue
