### ISSUE TITLE
Wrong arguments for `sign` ?

### ISSUE THREAD

**Issue by enriquepablo** [grantila/u2f-api#14]
Testing the library in chrome, I get an error response "bad request" (2) trying to authenticate (sign). This patch [1] fixes the issue for me.

Does it make sense, do I open a PR? And should the modules under dist/ be also patched?

1.- https://github.com/grantila/u2f-api/compare/master...enriquepablo:master

**Comment by grantila** [comment]
Interesting, indeed your fix is valid, and is aligned with the u2f 1.0 spec, I wonder have this have worked before in different browsers...
Which version of chrome are you using? Have this started to fail in recent versions of chrome?

I'm unable to test u2f now, I'm not using it myself, but I'm happy to fix this if you can ensure it works in Chrome and Firefox at least?

**Comment by enriquepablo** [comment]
At the moment I'm using Chromium 70, and everything works, and I have also tested successfully with Chrome at whatever version was current when I opened the issue last August.
Key registration has never worked for me without the patch.
I have also tested registering keys in firefox quantum 63 and it works without issues.
Thanks!

**Comment by Anonymous43523** [comment]
I appear to have fixed this issue while working on what looked like a bug in the Nextcloud twofactor_u2f app:

https://github.com/nextcloud/twofactor_u2f/issues/325

Here's the final code block around the u2f.sign function:

`var appId = signRequests[0].appId;`
`var challenge = signRequests[0].challenge;`
`let regKeys = signRequests.map(x => { return {keyHandle:x.keyHandle, version:x.version}; });`
`u2f.sign(appId, challenge, regKeys, callback, timeout);`

**Comment by grantila** [comment]
@enriquepablo
> Key registration has never worked for me without the patch
But this only fixes `sign()`, not `register()`...?

Also, @Anonymous43523 solution looks right, there shouldn't be any `signRequests[ 0 ].registeredKeys`. The question is why it failed to begin with, all you're doing with that `map` is basically to extract out `{ keyHandle, version }`, right? I'm adding `appId` which [is valid to have there](https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html#idl-def-RegisteredKey), and then all that's removed from `signRequests` array is the `challenge` field. Is that what makes it break? Funny...

Try 1.0.10 and see if that works better. (@enriquepablo I think what you send to `sign()` is not right).
