### ISSUE TITLE
Doesn't work with react

### ISSUE THREAD

**Issue by jpacora** [grantila/u2f-api#17]
I'm creating this with a create-react-app and axios. I'm using Chrome 70.0.3538.110. This is my code:
registerKey() {
    alert('ok')
    axios.get(`${window.Backend}/api/enroll`)
      .then(Response => {

        window.u2f.register("https://localhost:3000", [{version: "U2F_V2", appId: "https://localhost:3000", challenge: "6LZ9ejFafm8Od6vZY1haXnjkhPiipS9vxSqJ0EX79zI"}], [], function(Register) {
          console.log(Register)
        });

        alert(0)
      }).catch(err => {
        alert(err)
      })
  }
the alert gets fired and my u2f device still work with other sites but doesn't work with react.

**Comment by ebeal** [comment]
How are you importing the library? Right now it looks like you're just using the browser api not the u2f-api library.

**Comment by grantila** [comment]
Yeah you need to `require` or `import` this library and use a bundler like webpack or fusebox.
