### ISSUE TITLE
Unable to use with blahgeek/Safari-FIDO-U2F

### ISSUE THREAD

**Issue by ruimarinho** [grantila/u2f-api#2]
Due the UA sniffing, I am unable to use [blahgeek/Safari-FIDO-U2F](https://github.com/blahgeek/Safari-FIDO-U2F) when websites use this library. Would testing `window.u2f` be enough to detect support for U2F?

**Comment by grantila** [comment]
(Intentionally) blocked by https://github.com/Safari-FIDO-U2F/Safari-FIDO-U2F/issues/24
