### ISSUE TITLE
Register does not display Chrome's UI

### ISSUE THREAD

**Issue by matejdro** [grantila/u2f-api#25]
Not sure if I'm doing something wrong, but calling `u2fApi.register` will work just fine (it will return normally after pressing button on my U2F key), however, Chrome will not display any UI about this.

For example, when registering on [Yubikey demo site](https://demo.yubico.com/webauthn-technical/registration), Chrome will display this UI:

![image](https://user-images.githubusercontent.com/507922/71654667-4c01f480-2d33-11ea-8f60-1181248bcf93.png)

I cannot get this to display with this library. Firefox seems to work fine (it displays USB prompt).

Any ideas?

**Comment by xQsme** [comment]
same issue here, tried the plain API from google and it also suffers from the same issue

**Comment by grantila** [comment]
Is it perhaps Yubikey displaying this? u2f itself is not supposed (afaik) to display anything, it's up to you on your website to do so.

**Comment by matejdro** [comment]
But this is not website UI, it is native Chrome UI.
