### ISSUE TITLE
Add support for Safari 13

### ISSUE THREAD

**Issue by romanbracinik** [grantila/u2f-api#26]
Hi at first I want to thank you for great library. And I want to ask, do you plan add support for Safari 13 because it's already support FIDO2. https://www.reddit.com/r/yubikey/comments/bx3rcl/fido2_will_be_officially_supported_in_safari_13/

Thanks

**Comment by ruudboon** [comment]
See release notes as well. https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes

**Comment by rsm23** [comment]
Any plans for Safari 13 on MacOS?
