### ISSUE TITLE
Use the global `u2f` object if it’s available

### ISSUE THREAD

**Issue by chris-morgan** [grantila/u2f-api#3]
Firefox Nightly has u2f support behind an about:config flag and is expected to ship it in Firefox 58.

This library should be using the `u2f` global if it is available, and then and only then falling back to the dodgy google-u2f-api.js and the also dodgy isSupported function.

P.S. The Google u2f-api.js is *terrible* code. The very first line of it is broken: `var u2f = u2f || {};`.

**Comment by grantila** [comment]
Yeah, that's Google's code...

I'll have a look at Firefox Nightly and see what it's about.

May I ask where you got this information from? MDN has no documentation on it, and most information out there dates back to around 2014-2015.

**Comment by chris-morgan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1065729

**Comment by grantila** [comment]
Global `u2f` support is implemented since 0.1.0.

Firefox Nightly support is incomplete, if it is shipped without proper multi-facet support, please open a new bug.
