### ISSUE TITLE
isSupported() return false in my chrome

### ISSUE THREAD

**Issue by zheangrybear** [grantila/u2f-api#30]
Chrome Version: 89.0.4389.128
Development environment ：React
Import : yarn add u2f-api
Code:
import { isSupported } from 'u2f-api'
isSupported().then((d=>{
  console.log(d)://  show false
}))

What should I do to support my chrome browser？need help.

**Comment by grantila** [comment]
Are you using https?

**Comment by zheangrybear** [comment]
If isSupported() returns true, I will use https,It's not time to use https。

isSupported().then((d=>{
  if (d) {
      //I will use https here
 }else{
    // show alert
}
}))

I use https://demo.yubico.com/webauthn-technical/registration to test my browser is good

**Comment by zheangrybear** [comment]
isSupported() return true in my firefox browser ，but false in chrome browser.

**Comment by grantila** [comment]
Returning true in firefox is perhaps a mistake, it should return false if you're not under https, you can't use it under plain http anyway. Testing if the browser support this while under http is a bad idea, use https to get an accurate response.
