### ISSUE TITLE
Current typescript typings look broken

### ISSUE THREAD

**Issue by vanackere** [grantila/u2f-api#6]
Hi,

 Trying to use your library from typescript, it looks like the current Typescript exports do not work...

It is possible to somehow make it work by casting the default export as a function but this looks ugly:

```ts
import * as u2fapi from 'u2f-api'
import { API } from 'u2f-api'

const u2fAPI: API = (u2fapi as any)();
console.log(u2fAPI);
```
I suggest either removing the current broken typings, or trying to fix them.

Note : aside from that, I would suggest migrating your whole library to typescript, as this would get automatic proper bindings ;-)

**Comment by grantila** [comment]
Which version of u2f-api and TypeScript, and what's your tsconfig? I'm unable to reproduce, default-imports works fine. Explain what you mean with "broken typings".

Also, PR's are welcome.

**Comment by vanackere** [comment]
Well since I was not able to figure out how to use the typings properly... could you please provide a sample typescript code ?

Aside from that I'm using typescript 2.5.3 , and u2f-api 0.2.4.

It should also be noted that your local copy of google u2f api looks a bit outdated.
Your version: 
  https://github.com/grantila/u2f-api/blob/master/lib/google-u2f-api.js
The current release:
 https://github.com/google/u2f-ref-code/blob/master/u2f-gae-demo/war/js/u2f-api.js

My current code works fine using the polyfill from https://github.com/mastahyeti/u2f-api but I wanted to have proper typescript typings (that's why I tried your package in the first place)

**Comment by grantila** [comment]
Oh, it's on github even, and not something one has to extract from an obscure example page, lovely. Thanks for the link.

The unit tests (written in TypeScript) import the library using the default-export. It imports from `../../` which should be the same entry point as when you import from `u2f-api`. ES6 default exports are incompatible with CommonJS "require" which is the reason you might have problems. Check if it's entries in your `tsconfig` that causes this. Regardless, importing `* as u2f` and then calling `u2f` as a function is actually *proper TypeScript*, even if it's ugly.

**Comment by randallfox** [comment]
Tried to use this, but Chrome gets an error on the module and require commands in index.js and u2f-api.  js.  I can only guess that you either have experimental javascript features turned on in your Chrome browser, or you're transpiling using typescript?  I use typescript with Angular (v2 and greater) but it handles all the transpiling automagically so I'm a little lost on how to make your code work. (note: Im not using your code in Angular, I'm just trying to plug it directly into my html/browser and light it up).  Perhaps a demo of it working or instructions on how to make it work would be of use to people.  I think what you did is a great idea, and it would be better if I could get it working.  Thanks

**Comment by grantila** [comment]
You need to use a bundler (browserify, webpack, fusebox). There is currently no distributable single file to use, is this how you intended to use it?

**Comment by randallfox** [comment]
Not sure how I'm going to use it..  I was just looking at the different browser implementations.  I got Firefox v57 (nightly dev version) working with the standard/native implementation, no extra code needed and it looks spot on to the standard which was great, and now I started looking at Chrome, which I expected to be a standard/native  implementation as well, but it appears it's not that easy.  That's what brought me to the code here..   I guess I will try a bundler and see if that helps..  Thanks..  :-)
