### ISSUE TITLE
U2F API supported on Firefox Quantum v58+

### ISSUE THREAD

**Issue by dmaroulidis** [grantila/u2f-api#8]
Actually Firefox Quantum supports u2f from version 58 and upwards. You may want to fix your README.md

**Comment by gre** [comment]
@dmaroulidis have you been able to confirm the library works on Firefox? our current tests are negative at Ledger :'( https://github.com/LedgerHQ/ledgerjs/issues/89

**Comment by grantila** [comment]
Updated. @gre I have now tested FF58 (since fixing #9) and it works. However, it doesn't follow the *facet* part of the U2F spec, so multi-domain registrations work differently than in Chrome, but for basic setups it works fine.

**Comment by dmaroulidis** [comment]
You just need to set security.webauth.u2f to true, in about:config, but as was said previously the implementation isn't complete. Mozilla wants to support FIDO U2F v2 in Firefox, so they won't be completing the implementation of FIDO U2F v1.1
