### ISSUE TITLE
0.3.0 seems to crash

### ISSUE THREAD

**Issue by gre** [grantila/u2f-api#9]
We were depending on v0.2.7 for the library `@ledgerhq/hw-transport-u2f` and there seem to be a breaking change for us when moving to 0.3.0. It actually throw an error

<img width="669" alt="capture d ecran 2018-03-08 a 17 07 17" src="https://user-images.githubusercontent.com/211411/37162931-d1a560fc-22f6-11e8-9417-50c65412d087.png">

(and it also console.log something accidentally..)

I think there are bugs in the google u2f api code.

if you look at `u2f.getApiVersion` code, you can see it is used as receiving a `response => ..` callback [here](https://github.com/grantila/u2f-api/blob/e36f601c1ebae215fed728749667f2678b6a40b3/lib/google-u2f-api.js#L661-L662) which is correctly called with this signature in case of `port.getPortType` is true [here](https://github.com/grantila/u2f-api/blob/e36f601c1ebae215fed728749667f2678b6a40b3/lib/google-u2f-api.js#L800). However, in the other case, it is set to the callbackmap [here](https://github.com/grantila/u2f-api/blob/e36f601c1ebae215fed728749667f2678b6a40b3/lib/google-u2f-api.js#L804) , but this is wrong, because the callback map have a different signature: it actually receives `(error, response)` args as used [here](https://github.com/grantila/u2f-api/blob/e36f601c1ebae215fed728749667f2678b6a40b3/lib/google-u2f-api.js#L631).

what's even weird to me is that the code of google-u2f-api.js is not even the same as in the google library, there were probably a mistake during sync of the code, because in this file:  https://github.com/google/u2f-ref-code/blob/master/u2f-gae-demo/war/js/u2f-api.js#L612 callback is actually called with `(response)` there is never the first error parameter.

@icewind1991 have you tested the code?

**Comment by gre** [comment]
I'm not sure what that PR #7 was attempting to fix, but it's breaking everything, I suggest you revert & rollback to previous version of that google-u2f-api.js .

I have just attempted to upgrade myself the library [here](https://github.com/gre/u2f-api/tree/attempt-update) and error is gone but nothing is working, u2f never responses and ends with a `google-u2f-api.js:619 Unknown or missing requestId in response.` error.

I wonder about the current state of U2F API and if it's possible to use u2f without actually needing this google-u2f-api fallback implementation?

**Comment by ChristophWurst** [comment]
> I'm not sure what that PR #7 was attempting to fix

It attempted to fix u2f on mobile browsers using NFC.

But I agree, the PR seems to have broken this library completely. See my findings at https://github.com/nextcloud/twofactor_u2f/pull/107.

**Comment by ChristophWurst** [comment]
Tried to apply the changes from the new google u2f lib to the previous version of this repo but I'm not sure how the lib is supposed to be used. E.g. `sign` and `register` now take a `u2f.RegisteredKey` array which we'd have to add as new parameter of this library.
@gre do you have a better understanding of how both libraries work so that we could resolve this issue?

**Comment by grantila** [comment]
Sorry for the delay, I'll have a look at this on Monday.

**Comment by enriquepablo** [comment]
The 0.2.7 -> 0.3.0 upgrade is breaking (at least) token registration in chrome for me.

And on inspection the PR is adding a u2f.register function that is immediately masked by another definition of the same name, so it does not seem very correct.

**Comment by grantila** [comment]
I went ahead and rewrote most of this. The google chrome implementation is now left 1:1 in this repo with a separate patch (so we can all see what this library does to it).

The 1.x has this fixed (at least in my tests in Chrome and Firefox). Note though, 1.x has no custom promise library support, and has no cancellable promises. If you used that, you'll have to change that logic on your side.

If any related problems are still seen, please re-open this issue (or file a new one).

**Comment by ChristophWurst** [comment]
@grantila thank you very much. I can confirm that the 1.0.4 release fixed all the issues introduced by 0.3.0 and we can finally use u2f on Chrome and FF again. Ref https://github.com/nextcloud/twofactor_u2f/pull/116
